export type ToolCategory = "image-generation" | "image-editing" | "content-creation" | "document";

export interface Tool {
  id: string;
  name: string;
  description: string;
  icon: string;
  path: string;
  creditCost: number;
  free?: boolean;
  badge?: string;
  category: ToolCategory;
  seoKeywords?: string[];
  howToUse?: string[];
  faq?: { question: string; answer: string }[];
  nameTranslations?: Record<string, string>;
  descriptionTranslations?: Record<string, string>;
}

export const CATEGORIES: { id: ToolCategory; icon: string; nameKey: string }[] = [
  { id: "image-generation", icon: "🎨", nameKey: "categoryImageGeneration" },
  { id: "image-editing", icon: "✂️", nameKey: "categoryImageEditing" },
  { id: "content-creation", icon: "📝", nameKey: "categoryContentCreation" },
  { id: "document", icon: "📄", nameKey: "categoryDocument" },
];

export const tools: Tool[] = [
  {
    id: "ai-image-generator",
    name: "AI Image Generator",
    description: "Turn text into stunning AI images. No watermark, instant download.",
    icon: "🎨",
    path: "/tools/ai-image-generator",
    creditCost: 1,
    badge: "New",
    category: "image-generation",
    seoKeywords: ["ai image generator", "text to image", "ai art", "sdxl image generator"],
    howToUse: [
      "Write a detailed prompt describing the image you want to create.",
      "Select quality (Low/Medium/High), aspect ratio, and output format.",
      "Optionally upload a reference image for style guidance.",
      "Click Generate and wait for the AI to create your image.",
      "Download your generated image in your chosen format.",
    ],
    faq: [
      { question: "How does AI image generation work?", answer: "Our tool uses Stability AI's SDXL model to generate images from text prompts. It can also use reference images for style guidance." },
      { question: "What quality should I choose?", answer: "Low is fastest and cheapest. High produces the best detail but costs more credits and takes longer. Medium is a good balance." },
    ],
    nameTranslations: { es: "Generador de Imágenes IA", ar: "مولد الصور بالذكاء الاصطناعي" },
    descriptionTranslations: { es: "Convierte texto en impresionantes imágenes con IA.", ar: "حول النص إلى صور مذهلة بالذكاء الاصطناعي." },
  },
  {
    id: "avatar-generator",
    name: "AI Avatar Generator",
    description: "Transform your photos into cartoon, anime, or professional avatars.",
    icon: "👤",
    path: "/tools/avatar-generator",
    creditCost: 5,
    badge: "Popular",
    category: "image-generation",
    seoKeywords: ["avatar generator", "ai avatar", "cartoon avatar", "anime avatar"],
    howToUse: [
      "Upload a clear front-facing photo of yourself.",
      "Select an avatar style (Cartoon, Anime, Professional, etc.).",
      "Click Generate and wait for your avatar to be created.",
      "Download your new avatar in high resolution.",
    ],
    faq: [
      { question: "What photo works best?", answer: "A clear, front-facing photo with good lighting and no obstructions produces the best results." },
      { question: "How many styles are available?", answer: "6 styles: 3D Cartoon, Anime, Professional, Pixel Art, Watercolor, and Sketch." },
    ],
    nameTranslations: { es: "Generador de Avatares IA", ar: "مولد الصور الرمزية" },
    descriptionTranslations: { es: "Transforma tus fotos en avatares de dibujos, anime o profesionales.", ar: "حول صورك إلى صور رمزية كرتونية أو أنمي أو احترافية." },
  },
  {
    id: "background-remover",
    name: "Background Remover",
    description: "Remove image backgrounds instantly with one click.",
    icon: "✂️",
    path: "/tools/background-remover",
    creditCost: 2,
    badge: "Free",
    category: "image-editing",
    seoKeywords: ["remove background", "background remover", "ai background removal", "transparent background"],
    howToUse: [
      "Upload an image with a background you want to remove.",
      "Choose Auto mode for one-click removal, or Manual mode to paint areas to keep.",
      "Download the result with a transparent background.",
    ],
    faq: [
      { question: "What image formats are supported?", answer: "PNG, JPG, and WebP images up to 10MB." },
      { question: "How does Manual mode work?", answer: "Paint green strokes on areas you want to keep. The AI will process only those areas for precise background removal." },
    ],
    nameTranslations: { es: "Eliminador de Fondos", ar: "مزيل الخلفية" },
    descriptionTranslations: { es: "Elimina fondos de imágenes al instante con un clic.", ar: "أزل خلفيات الصور فورًا بنقرة واحدة." },
  },
  {
    id: "watermark-remover",
    name: "Watermark Remover",
    description: "Erase watermarks, logos, and text from images intelligently.",
    icon: "🖌️",
    path: "/tools/watermark-remover",
    creditCost: 3,
    category: "image-editing",
    seoKeywords: ["remove watermark", "watermark remover", "erase logo", "remove text from image"],
    howToUse: [
      "Upload an image with watermarks or unwanted objects.",
      "The AI will automatically detect and remove watermarks.",
      "For precise control, paint a mask over the area to remove.",
      "Download the cleaned image.",
    ],
    faq: [
      { question: "Can it remove any watermark?", answer: "The AI works best on semi-transparent watermarks and logos. Complex or opaque watermarks may require manual masking for best results." },
    ],
    nameTranslations: { es: "Eliminador de Marcas de Agua", ar: "مزيل العلامات المائية" },
    descriptionTranslations: { es: "Borra marcas de agua, logotipos y texto de imágenes inteligentemente.", ar: "امح العلامات المائية والشعارات والنص من الصور بذكاء." },
  },
  {
    id: "photo-restorer",
    name: "Photo Restorer",
    description: "Restore and colorize old, blurry, or damaged photos.",
    icon: "📷",
    path: "/tools/photo-restorer",
    creditCost: 5,
    category: "image-editing",
    seoKeywords: ["photo restoration", "restore old photo", "photo colorizer", "ai photo repair"],
    howToUse: [
      "Upload a damaged or old photo.",
      "Choose Auto mode for scratch/dust removal, or Face Pro for face enhancement.",
      "Download your restored photo.",
    ],
    faq: [
      { question: "Can it restore very damaged photos?", answer: "The AI can handle moderate damage like scratches and fading. Severely damaged photos may show limited improvement." },
    ],
    nameTranslations: { es: "Restaurador de Fotos", ar: "مُستعِد الصور" },
    descriptionTranslations: { es: "Restaura y colorea fotos antiguas, borrosas o dañadas.", ar: "استعد ولون الصور القديمة أو التالفة." },
  },
  {
    id: "pdf-to-word",
    name: "PDF to Word",
    description: "Convert PDF documents to editable Word (.docx) files.",
    icon: "📄",
    path: "/tools/pdf-to-word",
    creditCost: 0,
    free: true,
    category: "document",
    seoKeywords: ["pdf to word", "pdf converter", "pdf to docx", "free pdf conversion"],
    howToUse: [
      "Upload a PDF file (up to 20MB).",
      "For text-based PDFs, the text and formatting will be extracted automatically.",
      "For scanned/image-based PDFs, pages are embedded as images in the Word document.",
      "Download the .docx file and edit in Microsoft Word or Google Docs.",
    ],
    faq: [
      { question: "Is PDF to Word really free?", answer: "Yes! Text-based PDF conversion uses local processing and costs 0 credits. Scanned PDFs are also free — pages are embedded as images." },
      { question: "Can it handle scanned PDFs?", answer: "Yes, scanned PDFs are supported. Pages are rendered as images and placed into the Word document. OCR text extraction is not currently available." },
    ],
    nameTranslations: { es: "PDF a Word", ar: "PDF إلى Word" },
    descriptionTranslations: { es: "Convierte documentos PDF a archivos Word (.docx) editables.", ar: "حول مستندات PDF إلى ملفات Word (.docx) قابلة للتحرير." },
  },
  {
    id: "image-upscaler",
    name: "Image Upscaler",
    description: "Upscale images to higher resolution with AI.",
    icon: "🔍",
    path: "/tools/image-upscaler",
    creditCost: 2,
    badge: "New",
    category: "image-editing",
    seoKeywords: ["image upscaler", "upscale image", "ai upscale", "increase image resolution"],
    howToUse: [
      "Upload an image you want to enlarge.",
      "Choose Photo or Anime mode for best results.",
      "Select 2x or 4x upscaling factor.",
      "Download your high-resolution image.",
    ],
    faq: [
      { question: "How much can I upscale an image?", answer: "2x or 4x the original resolution. For best results, start with a reasonably clear image." },
    ],
    nameTranslations: { es: "Ampliador de Imágenes", ar: "مُكبِر الصور" },
    descriptionTranslations: { es: "Amplía imágenes a mayor resolución con IA.", ar: "كبر الصور إلى دقة أعلى بالذكاء الاصطناعي." },
  },
  {
    id: "style-transfer",
    name: "Style Transfer",
    description: "Apply artistic styles to your photos using AI.",
    icon: "🎭",
    path: "/tools/style-transfer",
    creditCost: 4,
    badge: "New",
    category: "image-generation",
    seoKeywords: ["style transfer", "ai art style", "photo to art", "neural style transfer"],
    howToUse: [
      "Upload a photo you want to stylize.",
      "Select one of 6 artistic styles.",
      "Click Generate and wait for the style to be applied.",
      "Download your stylized image.",
    ],
    faq: [
      { question: "What styles are available?", answer: "6 styles: Oil Painting, Watercolor, Sketch, Anime, Cyberpunk, and Vintage." },
    ],
    nameTranslations: { es: "Transferencia de Estilo", ar: "نقل النمط" },
    descriptionTranslations: { es: "Aplica estilos artísticos a tus fotos usando IA.", ar: "طبق أنماطًا فنية على صورك بالذكاء الاصطناعي." },
  },
  {
    id: "text-polish",
    name: "Text Polish & Rewrite",
    description: "Polish, rewrite, shorten, or expand your text with AI.",
    icon: "✨",
    path: "/tools/text-polish",
    creditCost: 3,
    badge: "New",
    category: "content-creation",
    seoKeywords: ["text polisher", "ai rewrite", "text improver", "ai writing assistant"],
    howToUse: [
      "Paste or type your text in the input area.",
      "Select a mode: Polish, Shorten, Expand, Formal, Casual, or Grammar Fix.",
      "Click Polish and the AI will process your text.",
      "Copy or use the polished result.",
    ],
    faq: [
      { question: "What languages are supported?", answer: "The tool auto-detects and supports English, Spanish, and Arabic. Other languages may work but with reduced quality." },
    ],
    nameTranslations: { es: "Pulidor de Texto", ar: "مُنقح النصوص" },
    descriptionTranslations: { es: "Pule, reescribe, acorta o expande tu texto con IA.", ar: "صقل أو أعد كتابة أو اختصر أو وسع نصك بالذكاء الاصطناعي." },
  },
  {
    id: "face-blur",
    name: "AI Face Privacy Blur",
    description: "Auto-detect faces and apply mosaic, gaussian, or pixelate blur. Add manual regions, undo, and download. Protect privacy instantly.",
    icon: "😷",
    path: "/tools/face-blur",
    creditCost: 2,
    badge: "New",
    category: "image-editing",
    seoKeywords: ["face blur", "privacy blur", "face pixelation", "blur faces online", "face mosaic", "hide face in photo", "ai face detection", "privacy photo tool"],
    howToUse: [
      "Upload a photo containing faces you want to obscure.",
      "The AI automatically detects all faces in the image.",
      "Choose a blur style: Mosaic, Gaussian Blur, or Pixelate.",
      "Toggle Preview to compare before/after results.",
      "Add manual blur regions by clicking and dragging on the image.",
      "Use Undo to remove individual regions, or Clear All to start fresh.",
      "Click Download to save the processed image (PNG, lossless).",
    ],
    faq: [
      { question: "How does face detection work?", answer: "We use computer vision (OpenCV Haar cascade) to automatically detect faces in your uploaded image. The detection works best on clear, front-facing portraits." },
      { question: "Can I manually add blur regions?", answer: "Yes! Use the manual selection tool to draw rectangles over any area you want to obscure — faces the AI missed, license plates, logos, or any sensitive content." },
      { question: "What blur styles are available?", answer: "Three styles: Mosaic (pixelated blocks), Gaussian (smooth blur), and Pixelate (cell-based color averaging). Each provides different levels of privacy protection." },
      { question: "How many credits does it cost?", answer: "Standard images (2 credits/image). High-resolution images (>3000px) or images with 5+ detected faces cost 4 credits. New users get 3 free trials." },
      { question: "What image formats are supported?", answer: "JPG, PNG, and WebP formats are supported. Images up to 10MB. Output is always lossless PNG for maximum quality." },
    ],
    nameTranslations: { es: "Difuminado Facial IA", ar: "تمويه الوجه بالذكاء الاصطناعي" },
    descriptionTranslations: { es: "Detecta rostros automáticamente y aplica desenfoque mosaico, gaussiano o pixelado.", ar: "اكتشف الوجوه تلقائيًا وطبق التمويه الفسيفسائي أو الغاوسي أو المنقط." },
  },
  {
    id: "text-to-speech",
    name: "AI Text to Speech",
    description: "Convert text into natural, human-like speech with AI voice synthesis.",
    icon: "🎙️",
    path: "/tools/text-to-speech",
    creditCost: 3,
    badge: "New",
    category: "content-creation",
    seoKeywords: ["text to speech", "ai voice generator", "text to audio", "tts", "speech synthesis"],
    howToUse: [
      "Type or paste the text you want to convert to speech.",
      "Select a language for proper pronunciation.",
      "Click Generate and wait for the AI to synthesize the audio.",
      "Play the audio preview or download the WAV file.",
    ],
    faq: [
      { question: "What languages are supported?", answer: "40+ languages including English, Spanish, Arabic, French, German, Italian, Japanese, Chinese, Korean, Portuguese, Russian, Turkish, Polish, Dutch, Czech, Hindi, and Hungarian." },
      { question: "How long can the text be?", answer: "Up to 2000 characters per generation. For longer texts, break them into smaller segments." },
      { question: "What format is the audio?", answer: "MP3 format — universal compatibility with all media players, phones, and editing software." },
    ],
    nameTranslations: { es: "Texto a Voz IA", ar: "النص إلى كلام" },
    descriptionTranslations: { es: "Convierte texto en voz natural con IA.", ar: "حول النص إلى كلام طبيعي بالذكاء الاصطناعي." },
  },
  {
    id: "image-description",
    name: "AI Image Describer",
    description: "Generate detailed image descriptions, alt text, and captions with AI vision.",
    icon: "🖼️",
    path: "/tools/image-description",
    creditCost: 2,
    badge: "New",
    category: "content-creation",
    seoKeywords: ["image description", "alt text generator", "ai image caption", "image to text", "photo description"],
    howToUse: [
      "Upload an image you want to describe.",
      "Optionally add a custom question or instruction for the AI.",
      "Click Generate and the AI will analyze your image.",
      "Get an ALT text for SEO and a detailed description of the image.",
    ],
    faq: [
      { question: "What does the AI analyze?", answer: "Powered by Meta Llama 3.2 Vision — it identifies objects, people, colors, composition, setting, mood, text, and more to generate accurate descriptions." },
      { question: "Can I ask specific questions about the image?", answer: "Yes! Use the optional prompt field to ask custom questions like 'What brand is the car?' or 'Describe the facial expression.'" },
      { question: "Is this good for SEO?", answer: "Absolutely. The ALT text format is specifically designed for image SEO and accessibility compliance." },
    ],
    nameTranslations: { es: "Descriptor de Imágenes IA", ar: "واصف الصور بالذكاء الاصطناعي" },
    descriptionTranslations: { es: "Genera descripciones detalladas, texto ALT y más con IA.", ar: "أنشئ أوصافًا مفصلة ونص ALT والمزيد بالذكاء الاصطناعي." },
  },
  {
    id: "colorizer",
    name: "B&W Photo Colorizer",
    description: "Bring black and white photos to life with natural, vibrant AI colorization.",
    icon: "🎨",
    path: "/tools/colorizer",
    creditCost: 2,
    badge: "New",
    category: "image-editing",
    seoKeywords: ["colorize black and white photo", "ai colorizer", "bw to color", "photo colorization", "colorize old photos"],
    howToUse: [
      "Upload a black and white photo.",
      "Click Generate and watch the AI bring it to life with color.",
      "Toggle between before/after to see the transformation.",
      "Download your colorized photo in high resolution.",
    ],
    faq: [
      { question: "What types of photos work best?", answer: "Clear, well-lit black and white photos produce the best results. Portraits, landscapes, and historical photos all colorize well." },
      { question: "How is this different from Photo Restorer?", answer: "Photo Restorer repairs damage like scratches and fading. Colorizer uses FLUX Kontext Pro — a state-of-the-art AI that adds realistic color while preserving every detail of the original photo." },
      { question: "How do I get the best colorization results?", answer: "Choose a style that matches your photo. Add an optional description like 'blue sky, green grass, red car' to guide the AI. More specific descriptions produce more accurate colors." },
      { question: "Can it colorize any black and white image?", answer: "Yes — old photos, historical images, artistic B&W photos, and even screenshots. The AI understands context to assign plausible colors." },
    ],
    nameTranslations: { es: "Colorizador de Fotos B&N", ar: "تلوين الصور بالأبيض والأسود" },
    descriptionTranslations: { es: "Da vida a fotos en blanco y negro con colorización IA.", ar: "أضف الحياة للصور بالأبيض والأسود بتلوين ذكي." },
  },
  {
    id: "object-remover",
    name: "AI Object Remover",
    description: "Remove unwanted objects, people, or text from photos with AI inpainting.",
    icon: "🧹",
    path: "/tools/object-remover",
    creditCost: 3,
    badge: "New",
    category: "image-editing",
    seoKeywords: ["remove objects from photo", "ai object remover", "remove person from photo", "inpainting", "clean up photos"],
    howToUse: [
      "Upload a photo with unwanted objects, people, or text.",
      "Paint a mask over the areas you want to remove.",
      "Click Remove and the AI will fill the area naturally.",
      "Download your cleaned-up photo.",
    ],
    faq: [
      { question: "What can I remove?", answer: "People, objects, text, logos, blemishes, power lines — anything you paint over. The AI fills the area with context-aware content." },
      { question: "How is this different from Watermark Remover?", answer: "Watermark Remover auto-detects watermarks and logos. Object Remover lets you manually paint what to remove — ideal for larger or irregular objects." },
      { question: "How should I paint the mask?", answer: "Rough strokes over the object work best. The AI needs some surrounding context to fill naturally. Avoid pixel-precise masking." },
    ],
    nameTranslations: { es: "Eliminador de Objetos IA", ar: "مزيل الكائنات بالذكاء الاصطناعي" },
    descriptionTranslations: { es: "Elimina objetos, personas o texto no deseados de tus fotos.", ar: "أزل الكائنات أو الأشخاص أو النصوص غير المرغوب فيها من صورك." },
  },
  {
    id: "article-generator",
    name: "AI Article Generator",
    description: "Generate complete, well-structured articles from a topic and keywords with AI.",
    icon: "📝",
    path: "/tools/article-generator",
    creditCost: 3,
    badge: "New",
    category: "content-creation",
    seoKeywords: ["article generator", "ai writer", "content generator", "blog post writer", "seo article tool"],
    howToUse: [
      "Enter a topic for your article — be specific for best results.",
      "Optionally add keywords and select a tone (Neutral, Professional, Casual, etc.).",
      "Click Generate and the AI will write a structured article with title, sections, and conclusion.",
      "Review the article, copy to clipboard, or download as a text file.",
    ],
    faq: [
      { question: "How do I get the best results?", answer: "Be specific with your topic. Instead of 'marketing', try 'how AI is transforming small business marketing in 2026'. Adding relevant keywords helps too." },
      { question: "How long are the generated articles?", answer: "Articles are typically 500-1500 words with 3-5 main sections. The AI adapts length based on topic complexity." },
      { question: "Can I use the articles commercially?", answer: "Yes! Content you generate belongs to you. Use it on your blog, website, or anywhere you need content." },
    ],
    nameTranslations: { es: "Generador de Artículos IA", ar: "مولد المقالات بالذكاء الاصطناعي" },
    descriptionTranslations: { es: "Genera artículos completos y bien estructurados a partir de un tema con IA.", ar: "أنشئ مقالات كاملة ومنظمة من موضوعك باستخدام الذكاء الاصطناعي." },
  },
];
